project:
  type: website
  output-dir: docs

website:
  title: "threat-hunting"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true

editor: visual

